// js/components/GallaxyOctopus.jsx
import React from 'react'
import Canvas from './Canvas'
import Setting from './settings/Setting'

export default class GallaxyOctopus extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            setting: {
                reverseGravity: true,
                pipeInterval: 1600,
                noHit: false
            }
        }
        React.initializeTouchEvents(true)
    }

    onChangeSetting(setting) {
        // set game parameter
        this.setState({ setting: setting }, () => {
            this.refs.canvas.reset()
        })
    }

    render() {
        return (
            <div>
                <Canvas ref="canvas" setting={this.state.setting}/>
                <Setting setting={this.state.setting} onChangeSetting={this.onChangeSetting.bind(this)} />
            </div>
        )
    }
}

// js/components/GallaxyOctopus.vue
<template>
  <div>
    test!!
  </div>
</template>

<script>
// import Canvas from './Canvas'
// import Setting from './settings/Setting'

export default {

  data () {
    return {
      setting: {
          reverseGravity: true,
          pipeInterval: 1600,
          noHit: false
      }
    }
  },

  computed: {

  },

  components: {
  },

  created () {
  },

  methods: {
    // onChangeSetting(setting) {
    //     // set game parameter
    //     this.setState({ setting: setting }, () => {
    //         this.refs.canvas.reset()
    //     })
    // }
  }
}
</script>
